### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by RPSMain** [fantalib/fanta#22]
# 0.2.0
- [ ] Move back to Account NOTE: (Might Not)
- [ ] Getting A Basic Bot With Client Working
- [ ] Full App Command Implementation
